### ISSUE TITLE
How to tell sider to ignore some files?

### ISSUE THREAD

**Issue by elshaddae** [sider/goodcheck#118]
Hello, first I can't find your support contact on the website. Please put something like your email address somewhere. I'm from China, the intercomcdn for chatbot or whatever is broken. So forgive me if this is wrong place, I've come a long way.

My small problem, I have tried sider recently I find it nice but how to let the checker to ignore some files e.g? JS minified files like library.min.js? Something similar to gitignore, I don't want sider to report issues on some files.

Please help me. Thank you!

**Comment by ybiquitous** [comment]
Hi @elshaddae,

Thanks for contacting us. We have an email address for supporting: support@sider.review
Could you please re-contact via the email address?

**Comment by elshaddae** [comment]
Okay thank you for your prompt response. If you got my question can you also please say something about it? @ybiquitous

**Comment by ybiquitous** [comment]
Yes, of course! I've responded to you via email.

**Comment by ybiquitous** [comment]
I've closed the issue because we will contact each other via email from now on.
