### ISSUE TITLE
How to show "justification" message with CLI command

### ISSUE THREAD

**Issue by LWisteria** [sider/goodcheck#206]
Hi, all.

I'm introducing goodcheck my project. It would be useful!

I have one question (request to support). Can you show me how to show the "justification" message on the result stdout?

I cannot find at
* https://github.com/sider/goodcheck/blob/e2b379dfdd5aa91bc9a3878c8f4c3db31a1cf5f8/docusaurus/docs/configuration.md
* https://github.com/sider/goodcheck/blob/e2b379dfdd5aa91bc9a3878c8f4c3db31a1cf5f8/docusaurus/docs/commands.md

It's great if the writer can know how to fix it at the same time the error output.

**Comment by gnakagaw** [comment]
@LWisteria

Hi. Thank you for using goodcheck!

> Can you show me how to show the "justification" message on the result stdout?

You can see `justification` with `goodcheck check --format=json`. Unfortunately, you cannot see `justification` with `--format=text` option.

Here is an example. 
```ShellSession
$ git clone https://github.com/sider/goodcheck && cd goodcheck
Cloning into 'goodcheck'...
remote: Enumerating objects: 2938, done.
remote: Counting objects: 100% (676/676), done.
remote: Compressing objects: 100% (294/294), done.
remote: Total 2938 (delta 331), reused 556 (delta 253), pack-reused 2262
Receiving objects: 100% (2938/2938), 2.12 MiB | 3.53 MiB/s, done.
Resolving deltas: 100% (1536/1536), done.
$ goodcheck check --format=json | jq .
[
  {
    "rule_id": "sider.goodcheck-rules.typo.github",
    "path": "README.md",
    "location": {
      "start_line": 7,
      "start_column": 29,
      "end_line": 7,
      "end_column": 34
    },
    "message": "Did you mean \"GitHub\"?",
    "justifications": [
      "When it means a third-party identifier (e.g., X-Github-Media-Type)."
    ],
    "severity": null
  },
  {
    "rule_id": "sider.goodcheck-rules.typo.github",
    "path": "docusaurus/docs/configuration.md",
    "location": {
      "start_line": 15,
      "start_column": 14,
      "end_line": 15,
      "end_column": 19
    },
    "message": "Did you mean \"GitHub\"?",
    "justifications": [
      "When it means a third-party identifier (e.g., X-Github-Media-Type)."
    ],
    "severity": null
  },
...
```

NOTE: Goodcheck homepage is available. You can see several examples and tips on that. 
https://sider.github.io/goodcheck/

**Comment by LWisteria** [comment]
@gnakagaw Thank you for quick response.

Do you plan to show the justification message on human-readable (format=text) output?
The writer will not use json format directly for his coding.

**Comment by gnakagaw** [comment]
@LWisteria 

> Do you plan to show the justification message on human-readable (format=text) output?

Sorry. We have no plan at this point. I opened a feature request issue. #207
Thank you for your helpful feedback.

**Comment by LWisteria** [comment]
@gnakagaw Thanks for your answer and new issue. Now it's clear so I'm closing this issue.
