### ISSUE TITLE
Output `justification` information with text output format

### ISSUE THREAD

**Issue by gnakagaw** [sider/goodcheck#207]
Now, we cannot see `justification` information with text output format. We have to use  json output format. It's reasonable to have a option to output `justification` even text output format.

Related: #206
Thanks to @LWisteria with a helpful feedback.

**Comment by ybiquitous** [comment]
I suggest the following example:

<img width="1238" alt="image" src="https://user-images.githubusercontent.com/473530/125710218-b71ab968-de65-4a87-ab73-ca9a4b43c81d.png">

Will this meet your requirements?

**Comment by gnakagaw** [comment]
@ybiquitous Thanks for a suggestion!

@LWisteria How about this? Would give us a feedback?

**Comment by LWisteria** [comment]
@ybiquitous @gnakagaw It looks good! How will multiple justification items be output?

```yaml
justification:
  - A should B
  - C will D
```

**Comment by ybiquitous** [comment]
@LWisteria Like this: ⬇️ 

<img width="858" alt="image" src="https://user-images.githubusercontent.com/473530/125750988-a95853ef-61fc-44a3-906b-8072f4ba45ee.png">

**Comment by LWisteria** [comment]
@ybiquitous That's great! I'm looking forward to merging #210.

**Comment by ybiquitous** [comment]
I've released [v3.1.0](https://rubygems.org/gems/goodcheck/versions/3.1.0)! 🎉
