### ISSUE TITLE
Possibility to relicense away from AGPL?

### ISSUE THREAD

**Issue by aergonaut** [sider/goodcheck#45]
At my company we are trying to incorporate Goodcheck into our build system, as we like its easy customization and compatibility with lots of different file types. However, the AGPL license is raising issues with our legal department, as our product is closed-source and our advisers are concerned about the implications of including AGPL software in our build system.

I fully understand that there are many reasons to choose AGPL over other licenses, and if the maintainers believe AGPL is the best choice for Goodcheck, then I will not try to convince anyone otherwise!

However, I would still like to ask if it would be possible to relicense Goodcheck to use a different license, such as the MIT license? Many Ruby projects use the MIT license, and I think the MIT license makes it easier for teams working on closed-source projects to use the code without legal concerns. It would certainly make it easier for my team to use the tool.

Thank you!

**Comment by soutaro** [comment]
I'm sorry for the late reply, @aergonaut.

It seems like your legal people are worrying about copyleft-ness of GPL to me, and I can understand their concern. One of the best options might be switching to MIT license as you say.

I cannot answer right now but will take time to choose the best license for the tool soon.

Thanks,

**Comment by ybiquitous** [comment]
@aergonaut Thanks for your suggestion and sorry for the too late reply.

We have updated the Goodcheck license to MIT as you suggested. We will release a new version including the license change soon.

**Comment by aergonaut** [comment]
Thank you!

**Comment by ybiquitous** [comment]
The version 2.4.3 has been released! 🎉 
https://github.com/sider/goodcheck/releases/tag/v2.4.3
