### ISSUE TITLE
Typo in link in README

### ISSUE THREAD

**Issue by tholok97** [sider/goodcheck#46]
Let me take the opportunity to say I really appreciate the tool :+1: While learning about it I found this (very minor) issue:

In the README there is a line that goes:
```
If you would not like to install Goodcheck to system (e.g. you would not like to install Ruby 2.4 or higher), you can use a docker image. [See below](#docker-image).
```
The link should be pointing to `#docker-images` instead?

(Thinking a PR would be overkill for this, but let me know if you'd prefer the change in that manner)

**Comment by ybiquitous** [comment]
Thank you so much for reporting! I fixed the typo. 😄
